export { default as TopDeals } from './TopDeals/TopDeals'
export { default as PopularProducts } from './PopularProducts/PopularProducts'
export { default as NewArrivals } from './NewArrivals/NewArrivals'
export { default as Item } from './ItemDetails/Item'
export { default as Cart } from './Cart/Cart'